Repository EntryDSM/Buldak, pull requests merged in 2022-07, with the labels that each got.

#13 marge(template): withTM emotion-style-provider 추가 및 ui 추가
  _templates/service/new/next.config.ejs.t
  apps/company/next.config.js
Labels: 🎨 Html&css

#21 merge(ui): Button 추가
  packages/ui/components/Button.tsx
  packages/ui/index.tsx
Labels: 🎨 Html&css

#19 merge(teacher): 기업 관리 페이지 추가
  apps/teacher/components/company/Box.tsx
  apps/teacher/components/company/index.tsx
  apps/teacher/package.json
  apps/teacher/pages/managementCompany.tsx
  package-lock.json
  yarn.lock
Labels: 🎨 Html&css

#17 merge(teacher) : 태그 관리 페이지 추가
  apps/teacher/components/AddInputButton.tsx
  apps/teacher/components/tag/index.tsx
  apps/teacher/pages/managementTag.tsx
Labels: 🎨 Html&css

#20 merge(teacher): pdf 모달 추가
  apps/teacher/components/student/pdf/Filter.tsx
  apps/teacher/components/student/pdf/StudentBox.tsx
  apps/teacher/components/student/pdf/index.tsx
  apps/teacher/components/student/pdf/studentList.tsx
  apps/teacher/pages/index.tsx
Labels: 🎨 Html&css

#18 feat(teacher): 기업 추가,추가 성공 모달,기업 정보 변경, 기업 정보 입력 페이지 퍼블리싱
  apps/teacher/components/company/AddCompany.tsx
  apps/teacher/components/company/CompanyInfo.tsx
  apps/teacher/components/company/EditInfo.tsx
  apps/teacher/components/company/SuccessModal.tsx
Labels: ✨ Featuredocumentation, 🎨 Html&css

#24 marge(ui): dropdown 추가
  packages/ui/assets/dropdown/Arrow.svg
  packages/ui/components/Dropdown.tsx
  packages/ui/index.tsx
  packages/ui/package.json
Labels: ✨ Featuredocumentation, 🎨 Html&css

#15 chore(setting-project): company 프로젝트 세팅
  apps/company/pages/_app.tsx
  apps/company/styles/globalStyle.ts
Labels: ⚙ Setting

#16 merge(company) : 메인 페이지 및 모달 퍼블리싱
  apps/company/assets/editmodal/Exit.png
  apps/company/assets/editmodal/Frame.jpg
  apps/company/components/editmodal/EditModal.tsx
  apps/company/components/studentbox/StudentBox.tsx
  apps/company/pages/_app.tsx
  apps/company/pages/list/index.tsx
Labels: 🎨 Html&css

#26 merge(ui): textBox 추가
  packages/ui/assets/textBox/error.svg
  packages/ui/assets/textBox/eye.svg
  packages/ui/assets/textBox/index.ts
  packages/ui/assets/textBox/non_eye.svg
  packages/ui/assets/textBox/search.svg
  packages/ui/components/Button.tsx
  packages/ui/components/TextBox.tsx
  packages/ui/index.tsx
Labels: 🎨 Html&css

#28 merge(teacher): 피드백 페이지 추가
  apps/teacher/components/company/AddCompany.tsx
  apps/teacher/components/company/Box.tsx
  apps/teacher/components/feedback/FeedbackArea.tsx
  apps/teacher/components/feedback/Header.tsx
  apps/teacher/components/student/Box.tsx
  apps/teacher/components/student/pdf/StudentBox.tsx
  apps/teacher/components/student/pdf/index.tsx
  apps/teacher/components/student/pdf/studentList.tsx
  apps/teacher/components/student/userDetail/DocumentList.tsx
  apps/teacher/components/student/userDetail/PersonalInfo.tsx
  apps/teacher/pages/feedback/[id].tsx
Labels: 🎨 Html&css

#27 merge(teacher): common에 있는걸로 치환
  apps/teacher/components/AddInputButton.tsx
  apps/teacher/components/SideBar.tsx
  apps/teacher/components/student/Box.tsx
  apps/teacher/components/student/Filter.tsx
  apps/teacher/components/student/pdf/index.tsx
  apps/teacher/components/student/userDetail/OptionButtons.tsx
  apps/teacher/components/student/userDetail/index.tsx
  apps/teacher/context/ModalContext.tsx
  apps/teacher/pages/_app.tsx
  apps/teacher/pages/index.tsx
Labels: 🎨 Html&css

#22 marge(ui): audio button box 추가
  packages/ui/components/Profile.tsx
  packages/ui/components/RadioButtonBox.tsx
  packages/ui/index.tsx
Labels: ✨ Featuredocumentation, 🎨 Html&css

#23 marge(ui): common tag 추가
  packages/ui/components/Tag.tsx
Labels: 🎨 Html&css

#31 merge(ui): dropdown, radiobutton, profile 로직 변경 및 스타일 변경
  packages/ui/components/Dropdown.tsx
  packages/ui/components/Profile.tsx
  packages/ui/components/RadioButtonBox.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#33 merge(ui): modal 추가
  packages/ui/assets/modal/close.svg
  packages/ui/assets/modal/index.ts
  packages/ui/components/Modal.tsx
  packages/ui/index.tsx
Labels: 🎨 Html&css

#30 @feat(student) : 페이지 에디터 추가
  apps/user/src/assets/svgs/AddElementBanner.tsx
  apps/user/src/assets/svgs/AddElementBlank.tsx
  apps/user/src/assets/svgs/AddElementBtn.tsx
  apps/user/src/assets/svgs/AddElementDefault.tsx
  apps/user/src/assets/svgs/AddElementDouble.tsx
  apps/user/src/assets/svgs/AddElementImage.tsx
  apps/user/src/assets/svgs/AddElementImageText.tsx
  apps/user/src/assets/svgs/AddElementLine.tsx
  apps/user/src/assets/svgs/AddElementList.tsx
  apps/user/src/assets/svgs/AddElementProject.tsx
  apps/user/src/assets/svgs/AddElementText.tsx
  apps/user/src/assets/svgs/AddElementTextImage.tsx
  apps/user/src/assets/svgs/AddPlusBtn.tsx
  apps/user/src/assets/svgs/EditerBanner.tsx
  apps/user/src/assets/svgs/EditerDoubleText.tsx
  apps/user/src/assets/svgs/EditerImage.tsx
  apps/user/src/assets/svgs/EditerText.tsx
  apps/user/src/assets/svgs/MeatballsMenu.tsx
  apps/user/src/assets/svgs/RepoLogo.tsx
  apps/user/src/components/header/Header.tsx
  apps/user/src/components/myPage/AddTagModal.tsx
  apps/user/src/components/myPage/EditPhoneNumber.tsx
  apps/user/src/components/myPage/EditProfile.tsx
  apps/user/src/components/myPage/ModalCommitBtn.tsx
  apps/user/src/components/myPage/ModalExplain.tsx
  apps/user/src/components/myPage/ModalSearchInput.tsx
  apps/user/src/components/myPage/RepresentativeModal.tsx
  apps/user/src/components/myPage/Technology.tsx
  apps/user/src/components/pageEditer/AddElement.tsx
  apps/user/src/components/pageEditer/AsideBar.tsx
  apps/user/src/components/pageEditer/ShowPage.tsx
  apps/user/src/pages/myPage/index.tsx
  apps/user/src/pages/pageEditer/index.tsx
Labels: 🎨 Html&css

#25 merge(student): 마이페이지 외 모달 2개 퍼블리싱
  apps/user/src/assets/Images/Profile.png
  apps/user/src/assets/Images/index.ts
  apps/user/src/assets/svgs/Arrow.tsx
  apps/user/src/assets/svgs/Close.tsx
  apps/user/src/components/myPage/EditPhoneNumber.tsx
  apps/user/src/components/myPage/MoveBox.tsx
  apps/user/src/components/myPage/RepresentativeModal.tsx
  apps/user/src/components/myPage/Technology.tsx
  apps/user/src/pages/myPage/index.tsx
Labels: 🎨 Html&css

#38 merge(ui): style 수정
  packages/ui/components/TextBox.tsx
Labels: 🎨 Html&css

#41 merge(teacher): 해상도에 따라 깨지는 버그 해결
  apps/teacher/components/AddInputButton.tsx
Labels: 🐞 BugFix

#42 docs(teacher): 모델 정의
  apps/teacher/models/default.ts
  apps/teacher/models/documents/responses.ts
  apps/teacher/models/tags/requests.ts
  apps/teacher/models/tags/responses.ts
  apps/teacher/models/teachers/requests.ts
  apps/teacher/models/teachers/responses.ts
Labels: 📃 Docs

#45 merge(teacher): Pdf 모달에서 학생 선택하는 기능 추가
  apps/main/package.json
  apps/teacher/components/student/pdf/StudentBox.tsx
  apps/teacher/components/student/pdf/index.tsx
  apps/teacher/components/student/pdf/studentList.tsx
  yarn.lock
Labels: ✨ Featuredocumentation

#48 merge(ui): modal 수정
  packages/ui/components/Modal.tsx
Labels: 🎨 Html&css

#44 merge(company): style 변경, type 추가
  apps/company/components/studentbox/StudentBox.tsx
  apps/company/pages/list/index.tsx
  apps/company/types/index.ts
Labels: 🎨 Html&css, ✅ Test

#47 merge(teacher): 달력 추가
  apps/teacher/components/Calendar.tsx
  apps/teacher/components/SideBar.tsx
  apps/teacher/components/company/AddCompany.tsx
  apps/teacher/components/student/userDetail/index.tsx
  apps/teacher/hooks/useCalendar.tsx
Labels: ✨ Featuredocumentation

#50 merge(teacher): api 관련 함수들 추가
  apps/teacher/api/axios.ts
  apps/teacher/api/default.ts
  apps/teacher/api/documents.ts
  apps/teacher/api/tags.ts
  apps/teacher/api/teachers.ts
  apps/teacher/models/teachers/responses.ts
  apps/teacher/package.json
Labels: 📬 API

#51 merge(Main): emotion컴포넌트 수정
  apps/main/components/FirstLoginPage/styled.ts
  apps/main/components/LoginPage/styled.ts
  apps/main/components/MainPage/CardBoxOne.tsx
  apps/main/components/MainPage/CardBoxTwo.tsx
  apps/main/components/MainPage/Footter.tsx
  apps/main/components/MainPage/MainPage.tsx
  apps/main/components/MainPage/styled.ts
  apps/main/components/SelectPage/SelectThings.tsx
  apps/main/components/SelectPage/styled.ts
  apps/main/pages/FirstLoginPage/Company/StageOne.tsx
  apps/main/pages/FirstLoginPage/Company/StageTwo.tsx
  apps/main/pages/FirstLoginPage/Student/StageOne.tsx
  apps/main/pages/FirstLoginPage/Student/StageThree.tsx
  apps/main/pages/FirstLoginPage/Student/StageTwo.tsx
  apps/main/pages/LoginPage.tsx
  apps/main/pages/SelectPage.tsx
Labels: 🔨 Refactor

#46 merge(user): 페이지 에디터 추가
  apps/user/package.json
  apps/user/src/assets/Images/Upload.png
  apps/user/src/assets/Images/index.ts
  apps/user/src/assets/svgs/AddElementClose.tsx
  apps/user/src/assets/svgs/BackSpace.tsx
  apps/user/src/assets/svgs/RepoLogo.tsx
  apps/user/src/components/header/BtnWrapper.tsx
  apps/user/src/components/header/Header.tsx
  apps/user/src/components/myPage/AddTagModal.tsx
  apps/user/src/components/myPage/EditPhoneNumber.tsx
  apps/user/src/components/myPage/ModalCommitBtn.tsx
  apps/user/src/components/myPage/ModalSearchInput.tsx
  apps/user/src/components/myPage/ModalType.tsx
  apps/user/src/components/myPage/MoveBox.tsx
  apps/user/src/components/myPage/RepresentativeModal.tsx
  apps/user/src/components/pageEditer/AddElement.tsx
  apps/user/src/components/pageEditer/AddElementModal.tsx
  apps/user/src/components/pageEditer/AsideBar.tsx
  apps/user/src/components/pageEditer/PatchAside.tsx
  apps/user/src/components/pageEditer/ShowPage.tsx
  apps/user/src/components/pageEditer/patchElement/Color.tsx
  apps/user/src/components/pageEditer/patchElement/Height.tsx
  apps/user/src/components/pageEditer/patchElement/Layout.tsx
  apps/user/src/components/pageEditer/patchElement/PatchElementWrapper.tsx
  apps/user/src/components/pageEditer/patchElement/UploadImage.tsx
  apps/user/src/constants/CompositionList.tsx
  apps/user/src/constants/ElementList.tsx
  apps/user/src/pages/_app.tsx
  apps/user/src/pages/pageEditer/index.tsx
Labels: 🎨 Html&css
