Repository EntryDSM/Buldak, pull requests merged in 2022-09, with the labels that each got.

#58 merge(teacher) : 기업 추가 api 연결
  .gitignore
  apps/main/components/AddInputButton.tsx
  apps/main/components/company/AddCompany.tsx
  apps/main/components/company/Box.tsx
  apps/main/components/company/CompanyInfo.tsx
  apps/main/components/company/EditInfo.tsx
  apps/main/components/company/SuccessModal.tsx
  apps/main/components/company/index.tsx
  apps/main/components/constant.ts
  apps/main/components/feedback/FeedbackArea.tsx
  apps/main/components/feedback/Header.tsx
  apps/main/components/student/pdf/Filter.tsx
  apps/main/components/student/pdf/StudentBox.tsx
  apps/main/components/student/pdf/index.tsx
  apps/main/components/student/pdf/studentList.tsx
  apps/main/components/tag/index.tsx
  apps/main/context/ModalContext.tsx
  apps/main/hooks/useModal.tsx
  apps/main/pages/add-company.tsx
  apps/main/pages/feedback/[id].tsx
  apps/main/pages/managementCompany.tsx
  apps/main/pages/managementTag.tsx
  apps/teacher/api/axios.ts
  apps/teacher/api/default.ts
  apps/teacher/assets/arrow.tsx
  apps/teacher/assets/compnayIcon.svg
  apps/teacher/assets/index.ts
  apps/teacher/assets/plusBlackIcon.svg
  apps/teacher/assets/plusIconWhite.svg
  apps/teacher/assets/studentIcon.svg
  apps/teacher/assets/tagIcon.svg
  apps/teacher/components/Calendar.tsx
  apps/teacher/components/SideBar.tsx
  apps/teacher/components/company/AddCompany.tsx
  apps/teacher/components/company/Box.tsx
  apps/teacher/components/company/CompanyInfo.tsx
  apps/teacher/components/company/index.tsx
  apps/teacher/components/constant.ts
  apps/teacher/components/student/Box.tsx
  apps/teacher/components/student/Filter.tsx
  apps/teacher/components/student/userDetail/DocumentList.tsx
  apps/teacher/context/ModalContext.tsx
  apps/teacher/hooks/useCalendar.tsx
  apps/teacher/hooks/useCompany.tsx
  apps/teacher/hooks/useModal.tsx
  apps/teacher/models/default.ts
  apps/teacher/models/teachers/requests.ts
  apps/teacher/utils/translate.ts
  packages/ui/components/TextBox.tsx
Labels: ✨ Featuredocumentation, 📬 API

#59 merge(teacher) : 기업 수정 api
  apps/teacher/api/axios.ts
  apps/teacher/api/default.ts
  apps/teacher/assets/close.svg
  apps/teacher/assets/index.ts
  apps/teacher/components/Calendar.tsx
  apps/teacher/components/SideBar.tsx
  apps/teacher/components/company/CompanyInfo.tsx
  apps/teacher/components/company/EditInfo.tsx
  apps/teacher/components/company/index.tsx
  apps/teacher/components/constant.ts
  apps/teacher/components/student/pdf/index.tsx
  apps/teacher/hooks/useCompany.tsx
  apps/teacher/models/default.ts
  apps/teacher/models/teachers/requests.ts
  apps/teacher/pages/_app.tsx
  apps/teacher/pages/index.tsx
  apps/teacher/pages/managementCompany.tsx
Labels: 📬 API

#63 merge(teacher) : 서버값 달력에 표시되게, 성공 모달 작동되게, 태그 삭제 작동
  apps/teacher/api/teachers.ts
  apps/teacher/assets/index.ts
  apps/teacher/assets/pdfArrow.svg
  apps/teacher/components/company/AddCompany.tsx
  apps/teacher/components/company/CompanyInfo.tsx
  apps/teacher/components/company/EditInfo.tsx
  apps/teacher/components/company/SuccessModal.tsx
  apps/teacher/components/student/index.tsx
  apps/teacher/components/student/pdf/index.tsx
  apps/teacher/components/student/pdf/studentList.tsx
  apps/teacher/components/student/userDetail/DocumentList.tsx
  apps/teacher/components/student/userDetail/OptionButtons.tsx
  apps/teacher/components/student/userDetail/PersonalInfo.tsx
  apps/teacher/components/student/userDetail/index.tsx
  apps/teacher/components/tag/index.tsx
  apps/teacher/context/ModalContext.tsx
  apps/teacher/hooks/useCalendar.tsx
  apps/teacher/hooks/useCompany.tsx
  apps/teacher/hooks/useModal.tsx
  apps/teacher/models/teachers/requests.ts
  apps/teacher/models/teachers/responses.ts
  apps/teacher/pages/add-company.tsx
  apps/teacher/pages/managementCompany.tsx
  apps/teacher/utils/translate.ts
Labels: ✨ Featuredocumentation, 📬 API

#66 merge(teacher) : 디테일 수정
  apps/teacher/api/axios.ts
  apps/teacher/assets/index.ts
  apps/teacher/assets/successCheck.svg
  apps/teacher/components/SideBar.tsx
  apps/teacher/components/company/CompanyInfo.tsx
  apps/teacher/components/company/EditInfo.tsx
  apps/teacher/components/company/index.tsx
  apps/teacher/components/modals/ModalHeader.tsx
  apps/teacher/components/modals/ModalWrapper.tsx
  apps/teacher/components/modals/SuccessModal.tsx
  apps/teacher/components/modals/pdf/Filter.tsx
  apps/teacher/components/modals/pdf/StudentBox.tsx
  apps/teacher/components/modals/pdf/index.tsx
  apps/teacher/components/modals/pdf/studentList.tsx
  apps/teacher/components/modals/userDetail/DocumentList.tsx
  apps/teacher/components/modals/userDetail/OptionButtons.tsx
  apps/teacher/components/modals/userDetail/PersonalInfo.tsx
  apps/teacher/components/modals/userDetail/index.tsx
  apps/teacher/hooks/useCompany.tsx
  apps/teacher/models/teachers/responses.ts
  apps/teacher/pages/add-company.tsx
  apps/teacher/pages/index.tsx
  apps/teacher/pages/management-company.tsx
  apps/teacher/pages/management-tag.tsx
  apps/teacher/utils/constant.ts
Labels: ✨ Featuredocumentation, 🔨 Refactor

#72 User my page api 연동
  apps/user/package.json
  apps/user/src/assets/svgs/Close.tsx
  apps/user/src/components/myPage/AddTagModal.tsx
  apps/user/src/components/myPage/EditPhoneNumber.tsx
  apps/user/src/components/myPage/EditProfile.tsx
  apps/user/src/components/myPage/ModalCommitBtn.tsx
  apps/user/src/components/myPage/ModalSearchInput.tsx
  apps/user/src/components/myPage/ModalType.tsx
  apps/user/src/components/myPage/RepresentativeModal.tsx
  apps/user/src/components/myPage/Technology.tsx
  apps/user/src/pages/_app.tsx
  apps/user/src/pages/myPage/index.tsx
Labels: 📬 API

#74 emotion-style-provider 스타일 추가
  package.json
  packages/emotion-style-provider/package.json
  packages/emotion-style-provider/src/global.ts
  packages/emotion-style-provider/src/index.tsx
Labels: ✨ Featuredocumentation

#81 merge(teacher) : 피드백 함수 연결
  apps/teacher/assets/feedbackArrow.svg
  apps/teacher/assets/index.ts
  apps/teacher/components/feedback/FeedbackComment.tsx
Labels: ✨ Featuredocumentation, 📬 API

#90 merge(teacher) : router 경로 수정
  apps/teacher/api/teachers.ts
  apps/teacher/hooks/useCompany.tsx
Labels: 🐞 BugFix

#97 merge(teacher) : 기업 생성 모달 닫을 때 기업 페이지로 리다이렉트
  apps/teacher/api/axios.ts
  apps/teacher/components/modals/ModalHeader.tsx
  apps/teacher/components/modals/ModalWrapper.tsx
  apps/teacher/components/modals/SuccessModal.tsx
  apps/teacher/package.json
  apps/teacher/pages/add-company.tsx
  apps/teacher/utils/cookie.ts
  yarn.lock
Labels: ✨ Featuredocumentation

#98 merge(teacher) : filter 로직 리팩토링
  apps/teacher/components/modals/ModalWrapper.tsx
  apps/teacher/components/modals/pdf/Filter.tsx
  apps/teacher/components/modals/pdf/index.tsx
  apps/teacher/components/student/Filter.tsx
  apps/teacher/components/student/index.tsx
  apps/teacher/hooks/useCompany.tsx
  apps/teacher/hooks/useStudentFilter.tsx
  apps/teacher/pages/index.tsx
Labels: 🔨 Refactor

#100 merge(teacher) : 에러 핸들러 추가
  apps/teacher/api/auth.ts
  apps/teacher/api/axios.ts
  apps/teacher/api/default.ts
  apps/teacher/components/company/AddCompany.tsx
  apps/teacher/components/company/CompanyInfo.tsx
  apps/teacher/components/company/EditInfo.tsx
  apps/teacher/components/feedback/FeedbackComment.tsx
  apps/teacher/components/feedback/Header.tsx
  apps/teacher/components/feedback/PageArea.tsx
  apps/teacher/components/student/Box.tsx
  apps/teacher/components/tag/index.tsx
  apps/teacher/hooks/useCompany.tsx
  apps/teacher/hooks/useStudentFilter.tsx
  apps/teacher/package.json
  apps/teacher/pages/_app.tsx
  apps/teacher/pages/management-company.tsx
  apps/teacher/pages/management-tag.tsx
  apps/teacher/utils/toast.ts
  yarn.lock
Labels: ✨ Featuredocumentation

#102 merge(teacher) : 에러 핸들러 수정
  apps/teacher/components/feedback/PageArea.tsx
  apps/teacher/components/modals/pdf/index.tsx
  apps/teacher/components/modals/userDetail/DocumentList.tsx
  apps/teacher/components/modals/userDetail/index.tsx
  apps/teacher/components/student/Box.tsx
  apps/teacher/components/student/index.tsx
  apps/teacher/components/tag/index.tsx
  apps/user/src/pages/index.tsx
Labels: 🔨 Refactor
